[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
config = { settings = { basedpyright = { analysis = { autoImportCompletions = true, typeCheckingMode = "standard", autoSearchPaths = true, useLibraryCodeForTypes = true, diagnosticMode = "openFilesOnly" } } } }

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

# [language-server.ruff.config.settings.lint]
# select = ["ALL"]

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
auto-format = true
file-types = [
  "py",
  "pyi",
  "py3",
  "pyw",
  "ptl",
  ".pythonstartup",
  ".pythonrc",
  "SConstruct",
]
shebangs = ["python"]
roots = [
  "setup.py",
  "setup.cfg",
  "pyproject.toml",
  "pyrightconfig.json",
  "Poetry.lock",
]
comment-token = "#"
language-servers = [
  # { name = "ruff", only-features = [ "format", "diagnostics", "code-action" ] },
  { name = "ruff" },
  { name = "basedpyright", except-features = [ "format" ] },
]
indent = { tab-width = 4, unit = "    " }
