name: Bump version

on:
  # push:
  #   branches:
  #     - 'master'
  schedule:
    - cron: '0 0 */3 * *' # every 3 days at midnight

jobs:
  bumpversion:
    name: Bump version if no commit for 3 days
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          fetch-depth: 0 # get all tags and branches
      - name: Check dates difference
        id: git-check
        run: |
          if git describe --exact-match 2> /dev/null; then
            # Tag exists already at the last commit
            echo is_stable="false" >> $GITHUB_OUTPUT
          else
            echo "Github last update : " +  $(git log -1 --format=%cd$)
            echo "Now : " +  $(date)
            now=$(date +%s)
            backupTime=$(git log -1 --format=%cd$ --date=raw | grep -o "^\w*\b")
            deltaDays=$((now-backupTime))
            deltaDays=$((deltaDays/3600/24))
            echo "Days since the last commit: $deltaDays"
            echo is_stable="$([ $deltaDays -ge 3 ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        if: steps.git-check.outputs.is_stable == 'true'
        shell: bash
        run: |
          # push: make sure Settings -> Actions -> General -> Workflow permission -> Read and write permission is set.
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          bash bump_version.sh 'No commits for more than 3 days'
