name: Bump version

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 */3 * *' # every 3 days at midnight

jobs:
  bumpversion:
    name: Bump version if no commit for 7 days
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      - name: Check dates difference
        id: git-check
        run: |
          if git describe --exact-match 2> /dev/null; then
            # Tag exists already at the last commit
            echo is_stable="false" >> $GITHUB_OUTPUT
          else
            echo "Github last update : " +  $(git log -1 --format=%cd$)
            echo "Now : " +  $(date)
            now=$(date +%s)
            backupTime=$(git log -1 --format=%cd$ --date=raw | grep -o "^\w*\b")
            deltaDays=$((now-backupTime))
            deltaDays=$((deltaHours/3600/24))
            echo "Days since the last commit: $deltaDays"
            echo is_stable="$([ $deltaDays -lt 7 ] && echo "true" || echo "false")" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        if: steps.git-check.outputs.is_stable == 'true'
        shell: bash
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0 --match 'v*' 2> /dev/null || true)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{OFS="."; $NF+=1; print $0}')
          if [[ -z $NEW_VERSION ]]
          then
            NEW_VERSION='v0.1.0'
          fi

          # push: make sure Settings -> Actions -> General -> Workflow permission -> Read and write permission is set.
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable
          git tag -a "$NEW_VERSION" -m "No commits for 7 days"
          git push origin "$NEW_VERSION"
